\pset border 2
WITH terms(cat, label, pat) AS (VALUES
 ('orchestration','LangChain','\mlangchain\M'),
 ('orchestration','LangGraph','\mlanggraph\M'),
 ('orchestration','LlamaIndex','llama[ -]?index'),
 ('orchestration','CrewAI','\mcrew ?ai\M'),
 ('orchestration','AutoGen','\mautogen\M'),
 ('orchestration','Semantic Kernel','semantic kernel'),
 ('orchestration','DSPy','\mdspy\M'),
 ('orchestration','Haystack','\mhaystack\M'),
 ('orchestration','MCP / Model Context Protocol','model context protocol|\mmcp\M'),
 ('agents','agent / agentic','\magent(s|ic)?\M'),
 ('agents','multi-agent','multi[ -]?agent'),
 ('agents','tool / function calling','(tool|function)[ -]calling'),
 ('agents','autonomous agents','autonomous agent'),
 ('agents','human-in-the-loop','human[ -]in[ -]the[ -]loop|\mhitl\M'),
 ('agents','workflow orchestration','workflow orchestrat'),
 ('rag','RAG','\mrag\M|retrieval[ -]augmented'),
 ('rag','vector database','vector (db|database|store|search)'),
 ('rag','embeddings','\membedding(s)?\M'),
 ('rag','pgvector','\mpgvector\M'),
 ('rag','Pinecone','\mpinecone\M'),
 ('rag','Weaviate','\mweaviate\M'),
 ('rag','Qdrant','\mqdrant\M'),
 ('rag','Chroma','\mchroma(db)?\M'),
 ('rag','FAISS','\mfaiss\M'),
 ('rag','reranking','\mre[ -]?rank'),
 ('rag','semantic search','semantic search'),
 ('rag','knowledge graph','knowledge graph'),
 ('models','OpenAI','\mopenai\M'),
 ('models','Anthropic / Claude','\manthropic\M|\mclaude\M'),
 ('models','Gemini / Vertex','\mgemini\M|vertex ai'),
 ('models','Llama','\mllama\M'),
 ('models','Mistral','\mmistral\M'),
 ('models','Hugging Face','hugging ?face'),
 ('models','LLM (any)','\mllm(s)?\M|large language model'),
 ('models','fine-tuning','fine[ -]?tun'),
 ('models','prompt engineering','prompt engineer'),
 ('models','GenAI','\mgen ?ai\M|generative ai'),
 ('models','multimodal','multi[ -]?modal'),
 ('quality','evaluation / eval','\meval(s|uation)?\M'),
 ('quality','LangSmith','\mlangsmith\M'),
 ('quality','LangFuse','\mlangfuse\M'),
 ('quality','Weights & Biases','weights ?& ?biases|\mwandb\M'),
 ('quality','guardrails','guardrail'),
 ('quality','hallucination','hallucinat'),
 ('quality','observability','observabilit'),
 ('quality','monitoring','\mmonitor(ing)?\M'),
 ('quality','A/B testing','a/b test'),
 ('quality','benchmark','\mbenchmark'),
 ('lang','Python','\mpython\M'),
 ('lang','TypeScript','\mtypescript\M'),
 ('lang','JavaScript / Node','\mjavascript\M|\mnode\.?js\M'),
 ('lang','Go','\mgolang\M|\mgo\M'),
 ('lang','Java','\mjava\M'),
 ('lang','Rust','\mrust\M'),
 ('lang','SQL','\msql\M'),
 ('infra','Docker','\mdocker\M'),
 ('infra','Kubernetes','\mkubernetes\M|\mk8s\M'),
 ('infra','AWS','\maws\M|amazon web services'),
 ('infra','GCP','\mgcp\M|google cloud'),
 ('infra','Azure','\mazure\M'),
 ('infra','Terraform','\mterraform\M'),
 ('infra','CI/CD','ci/cd|continuous (integration|deployment)'),
 ('infra','microservices','microservice'),
 ('infra','serverless','\mserverless\M'),
 ('infra','MLOps','\mmlops\M'),
 ('infra','LLMOps','\mllmops\M'),
 ('data','PostgreSQL','\mpostgres(ql)?\M'),
 ('data','Redis','\mredis\M'),
 ('data','Kafka','\mkafka\M'),
 ('data','Airflow','\mairflow\M'),
 ('data','Spark','\mspark\M'),
 ('data','Snowflake','\msnowflake\M'),
 ('data','dbt','\mdbt\M'),
 ('data','MongoDB','\mmongo(db)?\M'),
 ('api','REST API','\mrest(ful)?\M|\mapi(s)?\M'),
 ('api','GraphQL','\mgraphql\M'),
 ('api','gRPC','\mgrpc\M'),
 ('api','FastAPI','\mfastapi\M'),
 ('api','webhooks','\mwebhook'),
 ('prod','scalability','scalab'),
 ('prod','latency','\mlatenc'),
 ('prod','cost optimisation','cost (optimi|reduc|efficien)'),
 ('prod','production systems','production[ -](system|environment|grade|ready)'),
 ('prod','security','\msecurit'),
 ('prod','testing','\mtest(ing|s)?\M|\munit test'),
 ('prod','system design','system design|architectur'),
 ('prod','on-call','on[ -]call'),
 ('soft','stakeholder','stakeholder'),
 ('soft','ownership','\mownership\M|\mown the\M'),
 ('soft','cross-functional','cross[ -]functional'),
 ('soft','mentoring','\mmentor'),
 ('soft','startup / fast-paced','fast[ -]paced|\mstartup\M')
)
SELECT t.cat AS category, t.label AS skill,
  count(*) FILTER (WHERE j.description ~* t.pat) AS ai_track,
  round(100.0*count(*) FILTER (WHERE j.description ~* t.pat)/NULLIF(count(*),0),1) AS ai_pct
FROM terms t CROSS JOIN agents.job_applications j
WHERE j.track='ai' AND j.description IS NOT NULL
GROUP BY t.cat, t.label
ORDER BY ai_track DESC;
