/**
 * FounderOS — Documentation claim fitness function
 * ================================================
 * CI gate that makes a WRONG NUMBER IN THE DOCS a build failure.
 *
 * Why this exists (2026-08-28). A portfolio audit found the same quantity stated
 * five different ways across the recruiter-facing docs: the test count appeared as
 * 3,611 and 3,499; the test-file count as 337, 331, 329 and 321; the ATS board
 * registry as 623, 923, 297, 238, 200 and 142. Every one of those numbers had been
 * true on the day it was written. None of them were re-checked, because nothing
 * checked them. That is CLAUDE.md rule #27 in miniature — an unenforced rule
 * decays — and the cost is specific: a reader who catches one stale number stops
 * believing the other five, including the ones that are true and hard-won.
 *
 * Design. Two sources of truth, never a hand-maintained constant:
 *   1. docs/PROOF.md is GENERATED by `pnpm proof:scoreboard` from a real `vitest
 *      run`. It cannot drift from reality, so it is the truth for test counts.
 *   2. Everything else is measured from the repo at check time (git-tracked file
 *      counts, CSV rows, ADR files, the golden-task array).
 * Prose docs must agree with those. A claim this script cannot measure is not a
 * claim it polices — it stays silent rather than guessing.
 *
 * Scope is deliberately the RECRUITER PATH only (README + the docs it leads to).
 * Historical documents — docs/plans/, docs/sessions/, ADRs, archives — describe a
 * past state on purpose and are exempt by design, not by oversight.
 *
 * KNOWN GAP, stated rather than hidden. This proves the docs agree with
 * docs/PROOF.md; it does NOT prove PROOF.md is itself fresh. Add tests without
 * running `pnpm proof:scoreboard` and every check here still passes while the
 * published test count quietly falls behind. Closing it properly means asserting
 * against a live `vitest run`, and a static count of tests/ files does not
 * substitute — vitest's include/exclude config means the on-disk file count (339)
 * and the executed one (332) legitimately differ. Until then, regenerating the
 * scoreboard stays a step in the release flow, not something CI guarantees.
 *
 * Usage:
 *   node --import tsx/esm scripts/verify-doc-claims.ts
 *   node --import tsx/esm scripts/verify-doc-claims.ts --fix
 */

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");

/** Docs a recruiter is routed through. Historical docs are intentionally absent. */
const RECRUITER_PATH = [
  "README.md",
  "docs/EVAL.md",
  "docs/LIMITATIONS.md",
  "docs/ROADMAP.md",
  "docs/study/EVIDENCE-MAP.md",
  "docs/study/INTERVIEW-BRIEF.md",
  "docs/study/PORTFOLIO-GAPS-AND-ACTIONS.md",
];

interface Claim {
  /** Human name, used in the failure message. */
  readonly name: string;
  /** The measured truth. Throwing here means "cannot measure" and is fatal. */
  readonly measure: () => number;
  /** Each regex needs exactly one capture group holding the claimed number. */
  readonly patterns: readonly RegExp[];
  /** Docs to scan. Defaults to the recruiter path. */
  readonly files?: readonly string[];
  /** Why any file is excluded — required when `files` is narrower than the path. */
  readonly exemption?: string;
}

function read(relPath: string): string {
  return readFileSync(join(ROOT, relPath), "utf-8");
}

/** Strip thousands separators, including the `%2C` a shields.io badge URL encodes them as. */
function toNumber(raw: string): number {
  return Number.parseInt(raw.replace(/,|%2C/g, ""), 10);
}

/** The three ways a number appears in these docs: prose, bare, and badge-encoded. */
function renderings(value: number): readonly string[] {
  const grouped = value.toLocaleString("en-US");
  return [grouped, String(value), grouped.replace(/,/g, "%2C")];
}

/**
 * Test counts come from the generated scoreboard, never from a constant a human
 * could forget to bump. Line shape: "✅ 3645 tests / 331 files — all green".
 */
function fromProofScoreboard(): { tests: number; files: number } {
  const proof = read("docs/PROOF.md");
  const match = proof.match(/(\d[\d,]*) tests \/ (\d[\d,]*) files/);
  const tests = match?.[1];
  const files = match?.[2];
  if (tests === undefined || files === undefined) {
    throw new Error(
      "docs/PROOF.md has no '<N> tests / <M> files' line. It is generated — run `pnpm proof:scoreboard`.",
    );
  }
  return { tests: toNumber(tests), files: toNumber(files) };
}

function countGitTrackedSourceFiles(): number {
  // Counted the same way `git ls-files 'src/**/*.ts'` counts, without shelling out.
  const walk = (dir: string): number => {
    let total = 0;
    for (const entry of readdirSync(join(ROOT, dir), { withFileTypes: true })) {
      if (entry.name.startsWith(".")) continue;
      const rel = `${dir}/${entry.name}`;
      if (entry.isDirectory()) total += walk(rel);
      else if (entry.name.endsWith(".ts")) total += 1;
    }
    return total;
  };
  return walk("src");
}

function countAdrs(): number {
  return readdirSync(join(ROOT, "docs/decisions")).filter(
    (f) => f.endsWith(".md") && f !== "README.md",
  ).length;
}

function countGoldenTasks(): number {
  const src = read("src/eval/golden-tasks.ts");
  const body = src.match(/export const GOLDEN_TASKS[^=]*=\s*\[([\s\S]*?)\n\];/)?.[1];
  if (body === undefined) throw new Error("Could not locate GOLDEN_TASKS array in src/eval/golden-tasks.ts");
  return (body.match(/^\s{2}\{/gm) ?? []).length;
}

function countFreeBoards(): number {
  const csv = "docs/strategy/data/free-ats-boards.csv";
  if (!existsSync(join(ROOT, csv))) throw new Error(`Board registry missing at ${csv}`);
  return read(csv)
    .split(/\r?\n/)
    .slice(1)
    .filter((line) => line.trim().length > 0).length;
}

const CLAIMS: readonly Claim[] = [
  {
    name: "offline test count",
    measure: () => fromProofScoreboard().tests,
    patterns: [
      /(?<![+\-])\b(\d[\d,]*) (?:offline behavioural |unit\/kernel )?tests\b/g,
      // The README's shields.io badge, where the thousands comma is URL-encoded.
      /badge\/tests-(\d[\d]*(?:%2C\d{3})*)%20offline/g,
    ],
  },
  {
    name: "test file count",
    measure: () => fromProofScoreboard().files,
    patterns: [
      /\b(\d[\d,]*) files · \*{0,2}\d[\d,]* tests/g,
      /\b\d[\d,]* tests · (\d[\d,]*) files/g,
      /tests across (\d[\d,]*) files/g,
    ],
  },
  {
    name: "TypeScript source file count",
    measure: countGitTrackedSourceFiles,
    patterns: [/\b(\d[\d,]*) TypeScript source files/g, /Source \| (\d[\d,]*) files/g],
  },
  {
    name: "ADR count",
    measure: countAdrs,
    patterns: [/\b(\d[\d,]*) ADRs/g],
  },
  {
    name: "golden task count",
    measure: countGoldenTasks,
    patterns: [/\b(\d[\d,]*) golden tasks/g, /\b(\d[\d,]*)-task golden set/g],
  },
  {
    name: "free ATS board registry size",
    measure: countFreeBoards,
    patterns: [/\b(\d[\d,]*) ATS boards/g, /\b(\d[\d,]*) boards\b/g],
    // MARKET-2026 and study/README state the registry size AT COLLECTION TIME (623
    // boards, when the 911 postings were gathered). That is methodology, not drift:
    // rewriting it to today's number would misdescribe the study's own sample.
    files: RECRUITER_PATH,
    exemption: "docs/study/MARKET-2026-AI-ENGINEER.md and docs/study/README.md quote the registry size at collection time",
  },
];

export interface Violation {
  readonly claim: string;
  readonly file: string;
  readonly line: number;
  readonly claimed: number;
  readonly actual: number;
  readonly text: string;
}

export function checkClaim(claim: Claim): Violation[] {
  const actual = claim.measure();
  const violations: Violation[] = [];

  for (const file of claim.files ?? RECRUITER_PATH) {
    if (!existsSync(join(ROOT, file))) continue;
    const lines = read(file).split(/\r?\n/);

    lines.forEach((text, index) => {
      for (const pattern of claim.patterns) {
        // Patterns carry /g, so reset lastIndex before reusing across lines.
        pattern.lastIndex = 0;
        let match: RegExpExecArray | null;
        while ((match = pattern.exec(text)) !== null) {
          const raw = match[1];
          if (raw === undefined) continue;
          const claimed = toNumber(raw);
          if (claimed !== actual) {
            violations.push({ claim: claim.name, file, line: index + 1, claimed, actual, text: text.trim() });
          }
        }
      }
    });
  }
  return violations;
}

/** All violations across the registry. Exported so tests can assert the repo is clean. */
export function runChecks(): Violation[] {
  return CLAIMS.flatMap(checkClaim);
}

/**
 * Rewrite drifted numbers in place.
 *
 * Exact-match enforcement is only tolerable if fixing it is one command. A gate
 * that costs a manual edit on every test-adding PR gets switched off, and a
 * switched-off gate is how the docs drifted in the first place.
 */
function applyFixes(violations: readonly Violation[]): number {
  const byFile = new Map<string, Violation[]>();
  for (const v of violations) {
    byFile.set(v.file, [...(byFile.get(v.file) ?? []), v]);
  }

  let rewritten = 0;
  for (const [file, fileViolations] of byFile) {
    const lines = read(file).split(/\r?\n/);
    for (const v of fileViolations) {
      const index = v.line - 1;
      const current = lines[index];
      if (current === undefined) continue;
      // Replace only the offending literal, in whichever rendering it appears in,
      // leaving surrounding prose untouched.
      const stale = renderings(v.claimed);
      const fresh = renderings(v.actual);
      let updated = current;
      for (const [i, form] of stale.entries()) {
        if (updated.includes(form)) {
          updated = updated.replace(form, fresh[i] ?? String(v.actual));
          break;
        }
      }
      if (updated !== current) {
        lines[index] = updated;
        rewritten += 1;
      }
    }
    writeFileSync(join(ROOT, file), lines.join("\n"), "utf-8");
  }
  return rewritten;
}

function main(): void {
  const violations = runChecks();

  if (violations.length === 0) {
    console.log(`✅ doc-claims: ${CLAIMS.length} measured claims agree across ${RECRUITER_PATH.length} recruiter-path docs`);
    return;
  }

  if (process.argv.includes("--fix")) {
    const rewritten = applyFixes(violations);
    const remaining = runChecks();
    console.log(`🔧 doc-claims: rewrote ${rewritten} stale number(s); ${remaining.length} left`);
    if (remaining.length > 0) {
      for (const v of remaining) {
        console.error(`  ${v.file}:${v.line} — ${v.claim}: doc says ${v.claimed}, measured ${v.actual}`);
      }
      process.exit(1);
    }
    return;
  }

  console.error(`\n❌ doc-claims: ${violations.length} documented number(s) no longer match reality.\n`);
  for (const v of violations) {
    console.error(`  ${v.file}:${v.line} — ${v.claim}: doc says ${v.claimed.toLocaleString()}, measured ${v.actual.toLocaleString()}`);
    console.error(`    ${v.text.slice(0, 140)}`);
  }
  console.error(
    "\nFix the DOC, not this script: `pnpm verify:doc-claims --fix` rewrites these in place.\n" +
      "If the test counts moved, regenerate the source of truth first (`pnpm proof:scoreboard`).\n" +
      "A number in a portfolio doc is a claim, and a claim a reader can falsify in one\n" +
      "command costs more than it earns.\n",
  );
  process.exit(1);
}

// Run only when invoked directly; importing this module (tests) must not exit.
if (process.argv[1]?.endsWith("verify-doc-claims.ts") === true) main();
